name: Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Format Check
        run: cargo fmt -- --check
        
      - name: Check
        run: cargo check
      
      - name: Test
        run: cargo test
      
      - name: Run example - basic_usage
        timeout-minutes: 5
        run: |
          cargo run --example basic_usage
          
      - name: Run example - wallet_esplora_blocking
        timeout-minutes: 5
        run: |
          cargo run --example wallet_esplora_blocking